all:
	@g++ -std=c++11 -c computer.cpp -o lib/computer.o
	@g++ -std=c++11 -c player.cpp -o lib/player.o
	@g++ -std=c++11 -c game.cpp -o lib/game.o
	@g++ -std=c++11 main.cpp -o main lib/computer.o lib/player.o lib/game.o